###
POST http://localhost:3000/api/tickets
Content-Type: application/json

{
    "title": "Perut lapar",
    "description": "Duit tak cukup nak beli makanan",
    "category": "Other",
    "priority": 2,
    "progress": 90,
    "status": "done"
}

###
GET http://localhost:3000/api/tickets